// 语言包
let language = {
  zh:{
    1:'钱包',
    2:'请输入密码/私钥/地址',
    3:'使用keystore文件',
    4:'注册',
    5:'登录',
    6:'容量',
    7:'时间',
    8:'价格',
    9:'Keeper数量',
    10:'Provider数量',
    11:'天',
    12:'确定',
    13:'取消',
    14:'容量',
    15:'结束时间',
    16:'单位(1mb/天)价格',
    17:'确定',
    18:'取消',
    19:'我的钱包',
    20:'账号',
    21:'查看私钥',
    22:'导出keystore文件',
    23:'查询余额',
    24:'转账',
    25:'申请资金',
    26:'登出',
    27:'钱包',
    28:'查询余额',
    29:'转账',
    30:'订单',
    31:'文件',
    32:'申请存储',
    33:'申请存储列表',
    34:'申请存储',
    35:'订单',
    36:'质押',
    37:'查看所有keeper',
    38:'资格质押',
    39:'取消质押',
    40:'质押信息',
    41:'订单',
    42:'质押',
    43:'查看所有provider',
    44:'申请存储',
    45:'申请存储列表',
    46:'资格质押',
    47:'取消质押',
    48:'质押信息',
    49:'申请存储',
    50:'普通',
    51:'查看所有miner',
    52:'自定义押金',
    53:'使用默认押金算法',
    54:'要交多少押金才能挖矿',
    55:'申请矿工',
    56:'退出矿工',
    57:'查询我是不是矿工',
    58:'查询我抵押的金额',
    59:'私钥或地址错误',
    60:'keystore文件错误',
    61:'请输入密码',
    62:'确认',
    63:'取消',
    64:'密码错误',
    65:'交易hash',
    66:'合约地址',
    67:'创建时间',
    68:'大小',
    69:'存储时长(天)',
    70:'总价',
    71:'user',
    72:'keeper',
    73:'provider',
    74:'导出成功',
    75:'请输入对方信息',
    76:'对方账号',
    77:'转账金额',
    78:'确认',
    79:'取消',
    80:'请稍等,正在申请',
    81:'申请成功',
    82:'容量',
    83:'时间',
    84:'价格',
    85:'完成签署',
    86:'请稍等,正在申请',
    87:'申请成功',
    88:'容量',
    89:'结束时间',
    90:'单位价格',
    91:'自定义押金',
    92:'金额',
    93:'确认',
    94:'取消',
    95:'需要抵押的金额',
    96:'已抵押的金额',
    97:'您是矿工',
    98:'您不是矿工',
    99:'申请矿工',
    100:'金额',
    101:'确认',
    102:'取消',
    103:'没有私钥,请使用私钥登陆',
    104:'需交金额',
    105:'要抵押的金额',
    106:'查询质押空间需要抵押的金额',
    107:'要抵压的空间大小',
    108:'收益',
    109:'时间',
    110:'金额',
  },
  en:{
    1:'Wallet',
    2:'Please Input Your Password/Private Key/Address',
    3:'Use Keystore Files',
    4:'Register',
    5:'Login',
    6:'Capacity',
    7:'Time',
    8:'Price',
    9:'Keeper Number',
    10:'Provider Number',
    11:'Day',
    12:'Ok',
    13:'Cancel',
    14:'Capacity',
    15:'End Time',
    16:'Unit(1MB/Day) Price',
    17:'Ok',
    18:'Cancel',
    19:'My Wallet',
    20:'Account',
    21:'Show Private Key',
    22:'Export Keystore File',
    23:'Query Balance',
    24:'Transfer',
    25:'Get Coins',
    26:'Logout',
    27:'Wallet',
    28:'Query Balance',
    29:'Transfer',
    30:'Deal Order',
    31:'Documents',
    32:'Bid Order',
    33:'Bid Order List',
    34:'Bid Order',
    35:'Deal Order',
    36:'Pledge',
    37:'Show All Keepers',
    38:'Apply Pledge',
    39:'Cancel Pledge',
    40:'Pledge Information',
    41:'Deal Order',
    42:'Pledge',
    43:'Show All Providers',
    44:'Ask Order',
    45:'Ask Order List',
    46:'Apply Pledge',
    47:'Cancel Pledge',
    48:'Pledge Information',
    49:'Ask Order',
    50:'Ordinary',
    51:'Show All Miners',
    52:'Custom Deposit',
    53:'Use Default Deposit Algorithm',
    54:'How Much Deposit Will It Take To Dig',
    55:'Application For Miners',
    56:'Withdrawal Of Miners',
    57:"Find Out If I'm A Miner",
    58:'Query The Amount Of My Mortgage',
    59:'Private Key Or Address Error',
    60:'Keystore File Error',
    61:'Please Enter Your Password',
    62:'Confirm',
    63:'Cancel',
    64:'Password Error',
    65:'Transaction Hash',
    66:'Contract Address',
    67:'Creation Time',
    68:'Size',
    69:'Storage Time (Days)',
    70:'Total Price',
    71:'User',
    72:'Keeper',
    73:'Provider',
    74:'Export Success',
    75:"Please Enter The Other Party's Information",
    76:"The Other Party's Account",
    77:'Transfer Amount',
    78:'Confirm',
    79:'Cancel',
    80:"Just A Moment, Please. I'm Applying",
    81:'Successful Application',
    82:'Capacity',
    83:'Time',
    84:'Price',
    85:'Completion Of Signature',
    86:"Just A Moment, Please. I'm Applying",
    87:'Successful Application',
    88:'Capacity',
    89:'End Time',
    90:'Unit Price',
    91:'Custom Deposit',
    92:'Amount',
    93:'Confirm',
    94:'Cancel',
    95:'The Amount Of Collateral Required',
    96:'The Amount Mortgaged',
    97:"You're A Miner",
    98:"You're Not A Miner",
    99:'Application For Miners',
    100:'Amount',
    101:'Confirm',
    102:'Cancel',
    103:'No Private Key, Please Log In With The Private Key',
    104:'Need to pay the amount',
    105:'The amount to be pledged',
    106:'Check the amount of mortgage required for the pledge space',
    107:'The amount of space to offset',
    108:'Profit',
    109:'Time',
    110:'Money',
  },
  // 使用的语言
  lang:'zh'
}

let languagePack = {
  get(id){
    return language[language.lang][id]
  },
  // 设置当前语言环境
  setLang(lang){
    language.lang = lang
  },
  get lang(){
    return language.lang
  }
}

module.exports = languagePack